title: "Blog Anwar Hidayat"
description: "Blog Artikel Dinamis SEO Friendly"
url: "https://anwar-hidayat.github.io"
baseurl: ""

# Gunakan tema yang sangat stabil dan didukung resmi
remote_theme: jekyll/minima

# Cukup tuliskan plugins SATU KALI seperti ini
# Hapus jekyll-seo-tag dari daftar jika error berlanjut, 
# karena tema Minima terkadang sudah membawanya.
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Struktur Folder
include: [admin, _posts, assets]
exclude: [Gemfile, Gemfile.lock, vendor]
