# 1. Identitas Website
description: "Blog Artikel Dinamis SEO Friendly"
url: "https://anwar-hidayat.github.io"
baseurl: ""

# 2. Perbaikan Tema (Hapus remote_theme jika masih error)
# Kita gunakan tema internal GitHub Pages agar stabil 100%
theme: minima

# 3. Plugins (Tulis SATU KALI saja, tanpa list ganda)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 4. Pengaturan Artikel
permalink: /blog/:title/
collections:
  posts:
    output: true

# 5. Hilangkan File Konflik
# File-file ini sering membawa 'Hash' tersembunyi yang bikin error
exclude: 
  - Gemfile
  - Gemfile.lock
  - team.md
  - services.md
  - contact.md
  - vendor

sass:
  style: compressed # possible values: nested expanded compact compressed

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"
